include ../Makefile

BIN := $(HOME)/.local/bin

install:
	$(call link,$(BIN),gnome-randr)
	$(call link,$(BIN),screen-flip)

uninstall:
	$(call unlink,$(BIN),gnome-randr)
	$(call unlink,$(BIN),screen-flip)
