include ../Makefile

BIN := $(HOME)/.local/bin

install:
	$(call link,$(BIN),unsplash)
	$(call link,$(BIN),zero-two)
	$(call link,$(BIN),wall)

uninstall:
	$(call unlink,$(BIN),unsplash)
	$(call unlink,$(BIN),zero-two)
	$(call unlink,$(BIN),wall)
