#!/usr/bin/env bash

wall="$HOME/Pictures/Wallpapers/random.jpg"
size="$(xrandr --query | grep " connected" | head -1 | cut -d " " -f 3 | cut -d "+" -f 1)"

wget -O $wall https://source.unsplash.com/random/$size
wal --backend colorz --saturate 0.7 -i $wall --cols16 -o update-colors.sh
