#!/usr/bin/env bash

wall="$HOME/Pictures/Wallpapers/random.jpg"

wget -O $wall https://minimalistic-wallpaper.herokuapp.com/?random
wal --backend colorz --saturate 0.7 -i $wall --cols16 -o update-colors.sh
