#!/usr/bin/env bash

folder="$HOME/Pictures/Wallpapers/Darling/"
rand=$((($RANDOM)%(31)))
image=$(($((27))+$rand))

wall="${folder}$((image))"
wal --backend colorz --saturate 0.7 -i $wall --cols16 -o update-colors.sh
