include ../Makefile

install:
	$(call link,$(HOME),zshenv,.)
	$(call link,$(HOME),zshrc,.)
	$(call link,$(HOME),zlogout,.)

uninstall:
	$(call unlink,$(HOME),zshenv,.)
	$(call unlink,$(HOME),zshrc,.)
	$(call unlink,$(HOME),zlogout,.)
